# General Settings
data_root: "../../../../grace/u/geilender/"
seed: 42
num_workers: 8
verbose: 1
max_epochs: 3
max_ply: 300
clock_threshold: 30
chunk_size: 20000
start_year: 2019
start_month: 5
end_year: 2019
end_month: 5
from_checkpoint: false
checkpoint_epoch: 0
checkpoint_year: 2018
checkpoint_month: 5
num_cpu_left: 7
queue_length: 2

# Training Parameters
lr: 0.0001
wd: 0.00001
batch_size: 4096
first_n_moves: 10
last_n_moves: 10
train_ratio: 0.8

# Model Architecture
# dim_cnn: 128
# dim_vit: 512
# num_blocks_cnn: 5
# num_blocks_vit: 2
# input_channels: 18
# vit_length: 8
# elo_dim: 128

dim: 256
heads: 8
dim_head: 32
elo_dim: 128
mlp_dim: 512
input_channels: 18
num_layers: 8

# Feature and Loss Settings
side_info: true
side_info_coefficient: 1.0
value: true
value_coefficient: 1.0
max_games_per_elo_range: 20

#Smolgen settings
use_smolgen: true
smolgen_gen_size: 64
smolgen_per_square_dim: 16
smolgen_intermediate_dim: 128
